#!/bin/sh
# $Id: bootstrap,v 1.4 2007/07/06 17:37:00 jemarch Exp $
# Created 2003-08-29, Karl Berry.  Public domain.

if test "x$1" = x-n; then
  chicken=true
  echo "Ok, playing chicken; not actually running any commands."
else
  chicken=
fi

echo "Bootstrapping CVS GNU PDF Library with:"

# This overwrites lots of files with older versions.
# I keep the newest versions of files common between distributions up to
# date in CVS (see util/srclist.txt), because it's not trivial for every
# developer to do this.
#cmd="autoreconf --verbose --force --install --include=m4"

: ${ACLOCAL=aclocal}
: ${LIBTOOLIZE=libtoolize}
: ${AUTOHEADER=autoheader}
: ${AUTOMAKE=automake}
: ${AUTOCONF=autoconf}

# So instead:
cmd="$LIBTOOLIZE && $ACLOCAL -I m4 && $AUTOHEADER && $AUTOMAKE && $AUTOCONF"
echo "  $cmd"
$chicken eval $cmd || exit 1

echo
echo "Now run configure with your desired options, for instance:"
echo "  ./configure CFLAGS=-g"
echo
